Dockerfile

When attempting to use `gcloud app deploy` with a Flexible runtime (NodeJS in this case), the Dockerfiles/runtimes are not able to be found by the SDK. 
This PR sets the environment variable so that the SDK can find them and deploy using the App Engine dockerfiles.
Example drone deploy step
```yaml
deploy:
gae:
image: NYTimes/drone-gae
action: deploy
project: my-cool-project
version: "$$COMMIT"
addl_flags:
- "--stop-previous-version"
token: >
$$GOOGLE_CREDENTIALS
when:
event: push
```
Example App Engine yaml file
```yaml
runtime: nodejs
env: flex
threadsafe: true
service: my-cool-nodejs-project
```

Adds custom runtime path to use App Engine's flexible vm docker images.

---

Dockerfile

Updates from SDK 145.0.0 to 150.0.0. According to https://cloud.google.com/sdk/docs/release-notes there have been no breaking changes since for App Engine

Update gcloud sdk

---

README.md
exec.go
main.go
main_test.go

Work with Drone 0.6+, while still working with 0.4, but not 0.5 (because it's deprecated, according to the maintainers, and secrets are totally different than the other two).
Tested with `action: update` on:
0.4: https://drone-general-dev.newsdev.net/nytm/jryan-test/15
0.7: https://drone.dv.nyt.net/nytm/jryan-test/17
and added a few unit tests.
I'm not really familiar with all the ways people are using this, so other testing would be appreciated. This is available now on `jrynyt2/drone-gae:latest`

upgrade to 0.6+

---

main.go

Resolves #23. Tested on the original breaking drone job and it seems to work as expected with this change.

Check command is a string with length

---

.travis.yml

It's no longer necessary, and the latest travis build failed because of its presence
https://docs.travis-ci.com/user/docker/#Branch-Based-Registry-Pushes
Open `after success` on the docker step in https://travis-ci.org/NYTimes/drone-gae/builds/342502198
```
Successfully tagged nytimes/drone-gae:latest
unknown shorthand flag: 'e' in -e=[secure]
See 'docker login --help'.```

remove `-e` param from docker login command

---

main.go
main_test.go

Drone >0.4 will not expand env vars being passed into `vars`:
In this case, the value of `PASSWORD` in the app.yaml file would be `${PASSWORD}"`. 
.drone.yml
```
vars:
PASSWORD: ${PASSWORD}
```
app.yaml:
```
env_variables:
PASSWORD: {{ .PASSWORD }}
```
This PR expands env vars passed into `vars` so that if one exists for the value it'll be replaced.

expand env vars when passed into appengine vars

---

.travis.yml

Travis builds are passing even though docker builds have issues. Build the docker image during testing to verify.
For instance, this build 'passed' but the docker image build failed https://travis-ci.org/NYTimes/drone-gae/builds/352995451
Also update Go to 1.10 in travis. 
This should fail initially, because the GAE SDK isn't available for the version that gcloud is on. 
edit: this is the failure of this PR before a rebase https://travis-ci.org/NYTimes/drone-gae/builds/353014189

build docker image during tests to catch failures

---

main.go

When no flags were specified a blank argument would be added.  The AddlFlags were read in from the environment and then split which ends up with an array with ony empty string.  Added safety logic to ensure blank flags will not get added to the argument list

Fixing issue with AddlFlags.

---

Dockerfile
main.go

we've verified appcfg.py still works and this also works with the new go111 runtime.

using the gcloud sdk base image instead of installing the components ourselves

---

Dockerfile

After comparing image sizes, I found the `latest` image with all components already installed was smaller than the `alpine` image after installing the needed components, so just falling back to `latest`

pre-installing the GAE SDK for gcloud to avoid it happening on the fly

---

DOCS.md

Adds a link to GAE access control definitions and roles used/needed when deploying apps.

Add link to GAE SA roles

---

main.go
main_test.go

sanitizes the `version` field,
`feature/JIRA-123.5` => `feature-jira-123-5`

sanitize version

---

main.go
main_test.go

This PR adds the service field to be configurable on the gcloud command. It also splits the gcloud commands that respond to group or plain gcloud command because the syntax is different. I wasn't sure how I could write tests for this so any advice/suggestion welcome.
For example:
This is a group gcloud command:
`gcloud app versions delete <service> <version>`
whereas this is a plain gcloud command:
`gcloud app deploy <yml file> --version <version>`  
The group type doesn't support deploying with a yml file.
Here are the gcloud docs for reference:  https://cloud.google.com/sdk/gcloud/reference/app/

add service and a way to differentiate between gcloud groups and commands

---

go.mod
go.sum
main.go

Still need to verify it works, but looks to be a straightforward fix.

Adding hooks to use dispatch/cron yamls if referenced with deploy

---

exec.go
exec_test.go

Update regex so that in the Drone build output, the multiline JSON key is fully redacted. Previously was only redacting the first word of it. #37 for reference.

Redact multiline JSON strings in the output

---

Dockerfile

This will also force the main SDK to be built with the latest available version, which is not pinned

bumping to the latest SDK versions

---

Dockerfile

app engine SDK is not being updated regularly but we need to keep up
with gcloud sdk versions somehow. Bumping the version of cloud-sdk to
force a new build.
According to [this doc][old] the standalone app engine SDK will not be
available to download as of 2020 July 30. It has been deprecated as of
2019 July 30.
276 is the latest version as of today https://hub.docker.com/r/google/cloud-sdk/tags
[old]: https://cloud.google.com/appengine/docs/standard/python/sdk-gcloud-migration

Update cloud-sdk to 276

---

main.go
main_test.go

pick up GAE_CREDENTIALS for both drone 1.x and drone 0.x

---

main.go

Actions like `gcloud app services list` will fail with the addition of a
yaml file argument because it's arbitrary and unnecessary.
Use case:
I am trying to use `gcloud app services set-traffic` but I see the error:
```
ERROR: (gcloud.app.services.list) unrecognized arguments: ./app.yaml 
```
The command is configured properly with the exception of the `app.yaml` arg:
```
Running Command: gcloud app services set-traffic ./app.yaml MY_SERVICE --project MY_PROJECT --quiet --migrate --splits MY_COMMIT_SHA=1
```
Drone step is setup as follows:
```
- name: migrate-traffic
pull: if-not-exists
image: nytimes/drone-gae
settings:
action: services
sub_commands: set-traffic
addl_flags:
- --migrate
- --splits ${DRONE_COMMIT_SHA:0:8}=1
project: MY_PROJECT
service: MY_SERVICE
environment: …
```

Do not append yaml file to args if Action is a gcloudGroup

---

Dockerfile

Google will not be hosting cloud-sdk on docker hub after March 2021.
Also fixes the Drone build issue on main branch https://cloud.drone.io/nytimes/drone-gae/80/1/4 
https://hub.docker.com/r/google/cloud-sdk
> The Google Cloud SDK Docker image will cease being hosted on Docker Hub in March 2021. To continue using the Cloud SDK Docker Image, please use the image hosted on Google Container Registry by following the instructions located on the image's documentation page or GitHub page.
https://github.com/GoogleCloudPlatform/cloud-sdk-docker/releases
https://cloud.google.com/sdk/docs/downloads-docker

Update cloud-sdk to 328.0.0 and move to gcr-hosted image

---

DOCS.md
main.go
main_test.go

We'd like to have Drone secrets in base64 to be passed directly to the `GAE_CREDENTIALS` param.
The main use case is to integrate directly with the [Vault Google Cloud Secrets Engine](https://www.vaultproject.io/docs/secrets/gcp#service-account-keys) that returns the service account key in base64.
Example:
```
---
kind: secret
name: google_credentials_b64
get:
path: gcp/key/drone-gae-deployer
name: private_key_data
---
kind: pipeline
name: default
steps:
[...]
- name: deploy
pull: if-not-exists
image: nytimes/drone-gae
settings:
action: deploy
app_file: app.yaml
max_versions: 2
project: some-project
version: ${DRONE_COMMIT}
gae_credentials:
from_secret: google_credentials_b64
```

Enable service account keys to be provided in base64

---

Dockerfile

This reverts commit 748d2a31b5580d41454491c5be37d54a942b1de5.
@nyt-hughmandeville it seems like this version does not exist: https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.94.zip

Revert "updated Cloud and App Engine SDK versions. (#71)"

---

Dockerfile

Reverts nytimes/drone-gae#86
The upgrade of the GCP cloud-sdk base image has caused backwards incompatibility with users using `appcfg.py`, even though that is no longer supported.
For it to be released, it should be tested and we may have to tag a new major version of the plugin.

Revert "Update base docker image"

---

.github/workflows/build.yml

Reverts nytimes/drone-gae#108
Breaking changes

Revert "Bump slackapi/slack-github-action from 1.27.0 to 2.0.0"
